name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-versions: [ '3.1.x', '5.0.x', '6.0.x' ]
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true
    - name: Benchmark
      working-directory: test/benchmarks
      run: dotnet build -c Release & dotnet bin\release\net6.0\IndieSystem.Text.RegularExpressions.Benchmarks.dll --runtimes net461 netcoreapp3.1 net5.0 net6.0 --filter *AsmRegexBenchmark*
    - name: Create the package
      working-directory: src/
      run: dotnet pack --configuration Release
