name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Released .NET version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
    - name: Read version file
      id: verison_file
      uses: andstor/file-reader-action@v1
      with:
        path: "VERISON"
    - name: set version env
      run: echo " $VERISON "
      env:
        VERSION: ${{ steps.verison_file.outputs.contents }}.${{ env.GITHUB_RUN_ID }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=$VERSION
    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true
    - name: Benchmark
      working-directory: tests\benchmarks\
      run: dotnet bin\release\net6.0\IndieSystem.Text.RegularExpressions.Benchmarks.dll --runtimes net461 netcoreapp3.1 net5.0 net6.0 --filter *AsmRegexBenchmark*
    - name: Upload dotnet benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: tests\benchmarks\BenchmarkDotNet.Artifacts\
    - name: Create the package
      working-directory: src\
      run: dotnet pack --no-build --configuration Release -p:Version=$VERSION
    - name: Upload nuget package
      uses: actions/upload-artifact@v3
      with:
        name: IndieSystem.Text.RegularExpressions.$VERSION.nupkg
        path: src\bin\Release\IndieSystem.Text.RegularExpressions.$VERSION.nupkg